# Generated by Django 4.0.5 on 2022-06-28 12:13

import baseapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=10240, null=True, verbose_name='Описание')),
                ('meta_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='meta name')),
                ('meta_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='meta description')),
                ('cpu_slug', models.SlugField(blank=True, max_length=70, verbose_name='ЧПУ_Url')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to=baseapp.models.get_image_name, verbose_name='Изображение 800x530')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
