# Generated by Django 4.0.5 on 2022-07-06 12:04

import baseapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=baseapp.models.get_image_title_name, verbose_name='Изображение 800x530'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='parent_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='baseapp.portfolio_category', verbose_name='Категория'),
        ),
    ]
