# Generated by Django 4.0.5 on 2022-07-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_portfolio_category_alter_portfolio_picture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio_category',
            options={'verbose_name': 'Категория портфолио', 'verbose_name_plural': 'Категории портфолио'},
        ),
        migrations.AddField(
            model_name='portfolio_category',
            name='cpu_slug',
            field=models.SlugField(blank=True, max_length=150, verbose_name='Наименование eng'),
        ),
    ]
