# Generated by Django 4.0.5 on 2022-07-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_alter_portfolio_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='meta description')),
                ('meta_keywords', models.TextField(blank=True, max_length=1024, null=True, verbose_name='meta keywords')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
