# Generated by Django 4.0.5 on 2022-07-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_pages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
    ]
