# Generated by Django 4.0.5 on 2022-07-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_rename_pages_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='meta keywords'),
        ),
    ]
